\documentclass[draft]{compact_proposal}

\usepackage[utf8]{inputenc}
\usepackage[style=authoryear,isbn=false,url=false,maxcitenames=2,uniquename=false,uniquelist=false]{biblatex}
\addbibresource{reworking_enrichment.bib}
\usepackage[english]{babel}
\usepackage{fancyhdr}
\usepackage{blindtext}
\usepackage{xfrac}
\usepackage{siunitx}
\usepackage{xspace}
\usepackage[version=4]{mhchem}
\usepackage{wasysym}
\usepackage{gensymb}
\usepackage{xcolor}
\usepackage{subcaption}
\usepackage{multirow}

\graphicspath{{figures/}}

\newcommand{\R}[1]{\label{#1}\linelabel{#1}}
\newcommand{\del}[3]{\ce{\delta^#1#2_{#3}}}

\title{Climate-driven increases in channel mobility sequesters \\ coarse sediment in terrestrial floodplain deposits}
\author{Eric Barefoot, Jeff Nittrouer, Brady Foreman, Gerald Dickens, \textit{Liz Hajek + students}}
\date{\today}

<<setup, include=FALSE, cache=FALSE>>=
library(knitr)
# set global chunk options
opts_chunk$set(fig.path='figures/', fig.align='center', fig.show='hold', echo=FALSE, warning=FALSE, message=FALSE, error = FALSE, results='hide')
options(formatR.arrow=TRUE,width=90)
@

\begin{document}

\maketitle

<<initial_stuff>>=
remake_models_bool = FALSE
recalculate_stats = FALSE
library(here)
if (remake_models_bool)
{
  source(here('analysis', 'data_io', 'io_toolbox.r'))
} else if (recalculate_stats) {
  source(here('analysis', 'paleo_geoms', 'test_differences.r'))
  source(here('analysis', 'analyzing_reworking', 'test_differences.r'))
  source(here('figures', 'src', 'piceance_manuscript_data_plot.r'))
}
load(here('data','data_summaries', 'paleo_geom.rda'))
load(here('data','data_summaries', 'paleo_pres.rda'))
@

\section{Abstract}

The Paleocene-Eocene Thermal Maximum (PETM) is the most extreme example of an abrupt climate perturbation in the Cenozoic, and is widely cited as an analog for contemporary climate conditions and future change.
Accumulation of terrigenous mud in marginal shelf environments and coarsening in terrestrial deposits during the PETM are both thought to indicate increased water and sediment discharge from fluvial systems.
However, geochemical precipitation proxies and climate models support an alternative scenario, where the intra-annual variability of runoff increased while mean annual precipitation remained unchanged. 
Herein, we use measurements of channel geometry, sediment grain size, preservation of channel bar structures, and avulsion deposits to assess the fluvial response to hydrological change during the PETM from fluvial deposits in the Piceance Basin, western Colorado.
We find that the depth and slope of channel systems are consistent across the PETM interval, suggesting that overall water and sediment flux did not appreciably change.
In contrast, fluvial bar structures are poorly preserved during the PETM and avulsion style changes substantially, both indicating enhanced fluvial floodplain reworking due to accelerated channel migration and avulsion.
Taken together, these findings are consistent with an intensified hydrological regime characterized by increased precipitation variability without a change in mean runoff.
As a consequence of enhanced fluvial reworking, bed material sediment was partitioned into floodplain deposits, while mud was preferentially remobilized and transported downstream as washload.
This interpretation explains sedimentological variations in PETM stratigraphy across depositional environments without invoking sustained increases in sediment and water discharge.

\section{Introduction}

\R{A1} Contemporary global climate change is predicted to impact the hydrological cycle, threatening communities and infrastructure situated on river corridors \parencite[e.g.][]{dankers_climate_2008}.
The hazards posed by modern climate change can be better understood by analyzing the sedimentology and biogeochemical proxies preserved in continental margin stratigraphy, since both can be used to reconstruct hydrological changes in terrestrial environments \parencite[e.g.][]{slotnick_large_2012}.
However, stochastic sediment transport processes can distort and mask the signal of changing climate, hindering interpretations of the marine stratigraphic record \parencite{foreman_autogenic_2017, romans_environmental_2016, armitage_transformation_2011}.
Reconstructing the impacts of past climate change therefore depends on understanding how climate alters sediment production, transport, and deposition in terrestrial environments.

The Paleocene Eocene Thermal Maximum (PETM) is the most severe climate perturbation known in the Cenozoic Era \parencite{zachos_early_2008}.
Characterized by precipitation extremes, rapid warming, and accumulation of atmospheric carbon \parencite{carmichael_hydrological_2017}, the PETM is considered the best geologic analogue for contemporary climate warming \parencite{mcinerney_paleocene-eocene_2011}.
The PETM is identified in strata around the world by a negative carbon isotope excursion \parencite{kennett_abrupt_1991}, and often coincides with drastic changes in sedimentology.
In marginal marine environments, the PETM is most commonly associated with increased deposition of terrigenous clay \parencite{stassen_perturbation_2012, john_north_2008, slotnick_large_2012, gibson_stratigraphic_2000}, which is often attributed to elevated sediment flux from continents during the PETM: a so-called ``system-clearing'' event affecting rivers and floodplains on a global scale \parencite{foreman_fluvial_2012, jerolmack_shredding_2010}.

Studies of terrestrial alluvial systems generally find that strata deposited during the PETM are channel-dominated and coarser than bounding units \parencite[e.g.][]{schmitz_abrupt_2007, pujalte_massive_2015, foreman_climate-driven_2014}.
Differences in river channel geometries interpreted from the strata, including width and depth, as well as slope, are taken as evidence that water discharge increased during the PETM \parencite{foreman_fluvial_2012, chen_estimating_2018}.
Sediment flux is thought to have increased with discharge, allowing coarse sediment to \mnote[prograde]{``prograde'' is a relative word. It's prograding from wherever it was before. In a sense, it just means ``more distal'', so specifying from where doesn't mean much.} into alluvial basins, promoting fine sediment deposition downstream.
However, the paleohydraulic techniques used to reconstruct discharge carry significant uncertainty \parencite[e.g.][]{trampush_empirical_2014}, and competing scenarios are also plausible given the same data.

In particular, it remains unclear if sedimentological differences in PETM strata in fact represent a secular increase in the average discarge and sediment flux.
An alternative model argues that discharge averaged over annual to decadal time scales may have remained constant while runoff became more variable, perhaps via intensified monsoon seasons and more arid dry seasons.
Evidence from modern systems and the rock record suggests that river systems dominated by seasonal runoff differ in morphology and sedimentology from rivers with less variable flow \parencite{plink-bjorklund_morphodynamics_2015, fielding_role_2018}, and \textcite{esposito_sediment_2018} showed experimentally that introducing intense flooding while holding overall water and sediment flux constant caused channels to migrate more rapidly and avulse more frequently.
% \textcite{esposito_sediment_2018} showed experimentally that introducing intense flooding caused channels to migrate more rapidly and avulse more frequently as compared to a control where water and sediment flux were held constant, and the total water and sediment flux averaged over a given flood cycle was equivalent for both the flooding and control case.
\mnote[In the experiments, accelerated channel kinematics promoted floodplain reworking, which increased the concentration of channel deposits in the strata, reminiscent of channel-dominated strata observed in continental basins \parencite{pujalte_massive_2015, foreman_climate-driven_2014}.]{In the paper, they make no analysis of grain size actually, and no mention of export of fines, that is a novel finding to make in our experimental paper.}

Thus, coarse channel-dominated floodplain deposits observed in PETM strata could have arisen either from a secular increase in water and sediment flux or through intensified seasonal flooding with constant average discharge.
Distinguishing between these contrasting scenarios of fluvial response during the PETM is critical for interpreting sediment dispersal patterns and biogeochemical proxy data recorded in marine basins \parencite{foreman_autogenic_2017, trampush_identifying_2017, straub_influence_2013}.
In this study, we revisit the well-studied Piceance Basin (Colorado, USA), where changes in channel stacking patterns and sand enrichment have been attributed to increased water and sediment fluxes due to altered hydrology during the PETM \parencite{foreman_fluvial_2012}.

\section{Study Locality and Paleohydraulic Methods}

The impact of PETM-modulated hydrological changes on fluvial systems is assessed from studies in the Piceance Basin (Colorado, USA; Figure \ref{fig:map}).
As an intermontane Laramide depocenter active throughout the Paleogene \parencite{johnson_history_2003}, sedimentary fill of the Piceance Basin is conformable across the Paleocene-Eocene boundary.
The PETM interval is marked in the Piceance Basin by a distinctive \del{13}{C}{} isotope excursion, correlating with a distinctive sand-rich unit known as the Molina member of the Wasatch Formation \parencite{foreman_fluvial_2012}.

Juxtaposed between mud-rich units, sedimentological characteristics of the sandy Molina member contrast starkly with the underlying Atwell Gulch and the overlying Shire members of the Wasatch Formation \parencite{donnell_paleocene_1969}.
While the Atwell Gulch and Shire members largely consist of a matrix of muddy floodplain paleosols containing isolated channel sand bodies, the Molina member comprises interconnected, sheetlike amalgamated sand bodies with relatively thin intervening layers of floodplain mud.
\textcite{foreman_fluvial_2012} suggest that the distinctive changes observed in the Molina member are consistent with a fluvial response wherein enhanced precipitation evacuated sediment from hillslopes, at the same time that channels deepened and widened to convey a higher discharge.

However, paleohydraulic data from other localities present a more equivocal history of water discharge and sediment flux during the PETM \parencite[e.g.][]{chen_estimating_2018}.
Comparisons between these records and morphodynamic processes in the Piceance Basin are hindered by the limited channel geometry data available.
A more complete picture of channel morphodynamics can be gained by combining geometry-based methods with techniques to evaluate fluvial kinematics.
Work by \textcite{hajek_is_2014} suggests that the predominant avulsion style in an alluvial basin may be a characteristic of the channel-floodplain system, and \textcite{chamberlin_using_2019} show that a preponderance of poorly preserved or truncated bars in channel deposits can indicate the rate of fluvial reworking in the floodplain relative to the rate of subsidence.

We evaluate the impact of the PETM on fluvial systems in the Piceance Basin by quantifying four key paleohydraulic parameters in the Piceance Basin: (1) channel flow depth, (2) fluvial slope, (3) lateral migration, and (4) avulsion style.

Data were collected during three field campaigns from 2017--2019, as well as aggregated from previous literature and unpublished data.
Estimates of paleo-flow depth through the Wasatch Formation were obtained by measuring the relief on fully-preserved fluvial barforms for a total of \Sexpr{nnew} new flow depth estimates, nearly doubling the existing dataset \parencite{ethridge_reconstructing_1977, mohrig_interpreting_2000}.
These paleo-flow depths were combined with co-located measurements of bedload sediment size, interpreted using a hand lens and grain-size card, to estimate paleoslope via the empirical scaling of \textcite{trampush_empirical_2014}.
To estimate barform preservation and relative floodplain reworking, drone imagery was collected for 3 outcrops in the Piceance Basin, and photogrammetry was used to construct 3D digital models of the outcrop surface.
Bar clinoforms were mapped on the 3D digital outcrops, and barforms were classified as either fully preserved, partially preserved, or truncated, after \textcite{chamberlin_using_2019}.
Avulsion style was classified from field observations in all three members of the Wasatch formation using criteria in \textcite{jones_characterizing_2007}.

\section{Results}

The data indicate that paleoflow depths are statistically indistinguishable throughout the Wasatch Formation at a 95\% confidence level (Table \ref{tab:paleo_geom} and Figure \ref{fig:paleo_geom}a).
Additionally, estimates of paleoslope in the Piceance Basin indicate no difference between the Molina member and the bounding members at a 95\% confidence level (Figure \ref{fig:paleo_geom}b).
This demonstrates that within the resolution of currently available paleohydraulic methods, rivers were likely not substantially deeper or steeper during the PETM (Molina) as opposed to before (Atwell Gulch) or after (Shire).

Mapping of sedimentary structures throughout the Wasatch Formation shows that in the Molina member, \Sexpr{signif(pres$meanPres[2], digits = 3)}\% of barforms are fully preserved, whereas in the Atwell Gulch and Shire members, \Sexpr{signif(pres$meanPres[1], digits = 3)}\% and \Sexpr{signif(pres$meanPres[3], digits = 3)}\% of barforms are fully preserved, respectively (Figure \ref{fig:paleo_geom}c).
A~$\chi^2$~test shows that there are significantly fewer preserved barforms in the Molina member ($\chi^2$(\Sexpr{barpres_test$parameter},~n~=~\Sexpr{sum(barpres_test$observed)})~=~\Sexpr{signif(barpres_test$statistic, digits = 3)}, $\Sexpr{p_comp_reworking}$ (2-tailed)), indicating that barforms in the Molina member crosscut each other more frequently, and are less well preserved than in either the Shire or Atwell Gulch members.

\mnote[Our data also indicate that avulsion style changed during Molina time, and that incisional avulsions were more abundant than progradational avulsions.]{this is what we would like Liz to contribute}

\section{Discussion}

Elevated water and sediment fluxes due to the PETM have previously been invoked to explain the observed increase in sand concentration and amalgamation of channel deposits in the Molina member \parencite{foreman_fluvial_2012}.
However, the analysis of the Wasatch Formation in this study shows no detectable change in either channel depth or slope, both of which are predicted to adjust in tandem with an increase in discharge and sediment flux \parencite{leopold_hydraulic_1953}.
In fact, climate model simulations of the PETM generally predict overall drying conditions across the American Mountain West \parencite{carmichael_hydrological_2017}, and paleosol records in the Piceance Basin and nearby Bighorn Basin support the notion that regional mean annual precipitation did not increase during the PETM, and may have actually decreased slightly \parencite{kraus_transient_2007, lesko_increased_2019}

Without strong evidence for an overall increase in discharge during the PETM, the data in this study imply that precipitation seasonality may be the determining factor instead of mean annual precipitation.
In general, rivers subject to more variable flow tend to migrate more rapidly and avulse more often than rivers with low-variability flow \parencite{fielding_role_2018, leier_mountains_2005}.
Precipitation seasonality is primarily thought to affect channel dynamics via changes in floodplain vegetation \parencite{wing_plant_2013}, but experimental studies have demonstrated that increased lateral mobility of channels can occur in the absence of vegetation, with only a change in discharge variability \parencite{esposito_sediment_2018}.

As in the experiments, we observe a preponderance of channel deposits and truncated barforms during Molina time, suggesting that fluvial systems likely experienced accelerated channel migration during the PETM, which in turn drove heavy reworking of the near-surface floodplain stratigraphy.
Since fluvial channel deposits primarily consist of sand, reworking by channel migration reentrains mud and silt in overbank deposits, replacing fine material with coarser channel deposits and enriching the floodplain in sand.
Additionally, the switch from abrupt to transitional avulsions during Molina time suggests a fundamental shift in avulsion dynamics \parencite{jones_characterizing_2007, hajek_is_2014}.
Associated with progradational avulsions, crevasse splays are found more commonly in the Molina member, which is inferred to mean that coarse sediment was easily advected out of river channels during flooding events.
In contrast, the relative lack of crevasse splays and abundance of abrupt avulsions suggests in Atwell Gulch and Shire time, coarse sediment was confined to channels during floods while silt and mud were advected to the floodplain.
In the Wasatch Formation, basin-wide estimates of sediment thickness demonstrate the combined effect of these processes, where during the PETM (Molina), the stratigraphy consists of approximately \mnote[40\%]{check} sand, whereas before (Atwell Gulch) and after (Shire), only \mnote[20\%]{check} of the strata is sandy \parencite{donnell_paleocene_1969, johnson_history_2003}.

We therefore interpret that a climatically-modulated shift to more seasonal precipitation during the PETM led to an increase in lateral mobility and a switch to transitional-style avulsions, the combined effect of which was to partition sandy sediment preferentially to the floodplain, enriching floodplain deposits with sand.
In contrast, before and after the PETM, we interpret that the opposite is true: fine sediment was preferentially sequestered in the floodplain, while coarse sediment was confined to channels, which acted as conduits to advect sand downstream.
Despite regional heterogeneity in climate impacts during the PETM, most studies in continental basins observe coarsening in alluvial strata \parencite[e.g.][]{schmitz_abrupt_2007, pujalte_massive_2015}, and increased clay deposition in marginal marine strata \parencite[e.g.][]{john_north_2008}.
In a source-to-sink framework, increased fluvial reworking due to changes in precipitation seasonality during the PETM would sequester sand in floodplains, and promote mud bypass and deposition downstream.
While more analysis is needed to make a definitive connection, the conceptual model presented here could provide a mechanism to explain sedimentological trends in PETM stratigraphy, without invoking continent-scale increases in sediment and water flux.

\section{Conclusions and Implications}

In this study, paleohydraulic techniques were applied in the Piceance Basin of western Colorado to better constrain changes in channel-floodplain processes connected with abrupt climate change during the PETM.
The analysis of new data indicates that fluvial channel geometries such as depth and slope are consistent across the PETM boundary.
However, fluvial structures are more often truncated and cross-cut during the PETM interval, and avulsions become transitional in nature.
Taken together with experimental studies and new records of paleosol chemistry, these findings suggest that sedimentological shifts during the PETM in the Piceance Basin are not driven by overall increases in water and sediment flux, but rather by accelerated channel migration and a shift in avulsion style.

The Piceance Basin serves as an example that, all else being equal, terrestrial floodplains subjected to seasonally intense precipitation experience accelerated channel dynamics, allowing rivers to rework floodplain deposits, enriching the stratigraphy in sand.
As a corollary, reworked mud and silt that would be sequestered in the floodplain is bypassed downstream.
In contrast, channels in alluvial basins with low discharge variability can act as conduits for sand to bypass terrestrial floodplains and be deposited on shorelines and in marine basins.
This framework is advanced as an alternative to the ``global system-clearing event'' model of PETM landscape response, emphasizing that shifting hydrological regimes under global warming need not invoke transiently high sediment fluxes, but rather may simply re-apportion sediment through preferential partitioning.

\newpage

\begin{figure}[H]
	\centering
	\includegraphics[width = 6in, draft = false]{manuscript_map.pdf}
	\begin{minipage}{0.9\textwidth}
	\vspace*{2mm}
	\caption{The Piceance Basin is located in western Colorado, shown in the inset in dark grey, with key nearby cities and towns.
  The Wasatch Formation is exposed as shown in the grey shading in the map, surrounding the town of De Beque, and outcropping along the I-70 corridor.
  Color-coded dots indicate outcrops that were analyzed for this study.
  The color scheme is consistent through the paper, where yellow will always signify the Shire member, green the Molina, and blue the Atwell Gulch.
  }
	\label{fig:map}
	\end{minipage}
\end{figure}

\begin{figure}[H]
	\centering
	\includegraphics[width = 4.5in, draft=false]{annotated_outcrops_figure.pdf}
	\begin{minipage}{0.9\textwidth}
	\vspace*{2mm}
	\caption{Example outcrops showing key sedimentological features in each member of the Wasatch Formation.
  Color-coded lines indicate high-order bounding surfaces between channel storeys, whereas the white lines in each photograph indicate bar faces and scour surfaces.
  Note the neatly stacking clinoform bar faces in the Atwell Gulch and Shire members, indicating full preservation.
  In contrast, extensively cross-cutting bar scours and faces in the Molina member indicate scour and truncation.}
	\label{fig:outcrops}
	\end{minipage}
\end{figure}

\begin{figure}[H]
	\centering
	\includegraphics[width = 0.9\textwidth, draft=false]{petm_data.pdf}
	\begin{minipage}{0.9\textwidth}
	\vspace*{2mm}
	\caption{Estimates of paleohydraulic parameters in the Piceance Basin.
  Paleoflow depth is consistent across all three members of the Wasatch Formation, as is paleoslope.
  The Molina member shows significantly fewer fully preserved bars as opposed to the Atwell Gulch or Shire members.
  Additionally, the Molina member experiences many more transitional-type avulsions.}
	\label{fig:paleo_geom}
	\end{minipage}
\end{figure}

\begin{table}[H]
\centering
\caption{Data for Wasatch Formation in the Piceance Basin.
Included for each member of the Formation are paleoflow depths measured from barforms, paleoslopes, the proportion of fully preserved bars, the prevalance of transitional avulsions, and the associated uncertainty for each term.
The second part of the table indicates significance values for Conover-Iman tests comparing flow depths and slope in different members of the Wasatch Formation, as well as results from a $\chi^2$ test for the proportion of fully preserved bars and abundance of avulsion styles.}
\begin{tabular}{lllll}
Formation & Depth (m) $\pm \sigma$  & Slope (--) $\pm \sigma$ & \% reworked bars $\pm \sigma$ & avulsion style \\
\hline
Shire         &
\Sexpr{signif(geoms$meanDepth[3], digits = 3)} $\pm$ \Sexpr{signif(geoms$sdDepth[3], digits = 3)}  &
\Sexpr{signif(geoms$meanSlope[3], digits = 3)} $\pm$ \Sexpr{signif(geoms$sdSlope[3], digits = 3)} &
\Sexpr{signif(pres$meanPres[3], digits = 3)} $\pm$ \Sexpr{signif(pres$sdPres[3], digits = 3)} &
? $\pm$ ? \\
Molina        &
\Sexpr{signif(geoms$meanDepth[2], digits = 3)} $\pm$ \Sexpr{signif(geoms$sdDepth[2], digits = 3)}  &
\Sexpr{signif(geoms$meanSlope[2], digits = 3)} $\pm$ \Sexpr{signif(geoms$sdSlope[2], digits = 3)}  &
\Sexpr{signif(pres$meanPres[2], digits = 3)} $\pm$ \Sexpr{signif(pres$sdPres[2], digits = 3)} &
? $\pm$ ? \\
Atwell Gulch  &
\Sexpr{signif(geoms$meanDepth[1], digits = 3)} $\pm$ \Sexpr{signif(geoms$sdDepth[1], digits = 3)}  &
\Sexpr{signif(geoms$meanSlope[1], digits = 3)} $\pm$ \Sexpr{signif(geoms$sdSlope[1], digits = 3)}  &
\Sexpr{signif(pres$meanPres[1], digits = 3)} $\pm$ \Sexpr{signif(pres$sdPres[1], digits = 3)} &
? $\pm$ ? \\
\hline
Atwell Gulch -- Molina  & $\Sexpr{p_comp_AG_M}$ & $\Sexpr{p_comp_AG_M_slope}$  &
\multirow{3}{*}{$\Sexpr{p_comp_reworking}$} & \multirow{3}{*}{$p = ??$} \\
Shire -- Molina         & $\Sexpr{p_comp_AG_S}$ & $\Sexpr{p_comp_AG_S_slope}$  & & \\
Atwell Gulch -- Shire   & $\Sexpr{p_comp_S_M}$  & $\Sexpr{p_comp_S_M_slope}$   & & \\
\hline
\end{tabular}
\label{tab:paleo_geom}
\end{table}

\newpage

\printbibliography
%
\end{document}
