\documentclass[draft, 11pt, nonotes]{compact_proposal}

\usepackage[utf8]{inputenc}
\usepackage[style=authoryear,isbn=false,url=false,maxcitenames=2,uniquename=false,uniquelist=false]{biblatex}
\addbibresource{reworking_enrichment.bib}
\usepackage[english]{babel}
\usepackage{fancyhdr}
\usepackage{blindtext}
\usepackage{xfrac}
\usepackage{siunitx}
\usepackage{xspace}
\usepackage[version=4]{mhchem}
\usepackage{wasysym}
\usepackage{gensymb}
\usepackage{xcolor}
\usepackage{subcaption}
\usepackage{multirow}
\usepackage{rotating}

\graphicspath{{figures/}}

\newcommand{\R}[1]{\label{#1}\linelabel{#1}}
\newcommand{\del}[3]{\ce{\delta^#1#2_{#3}}}

\title{Enhanced lateral mobility in rivers caused grain-size sorting in floodplains \\
due to precipitation seasonality during the PETM }
\author{Eric A. Barefoot, Jeffrey A. Nittrouer, Brady Z. Foreman, Elizabeth A. Hajek, Gerald R. Dickens}
\date{\today}

<<setup, include=FALSE, cache=FALSE>>=
library(knitr)
# set global chunk options
opts_chunk$set(fig.path='figures/', fig.align='center', fig.show='hold', echo=FALSE, warning=FALSE, message=FALSE, error = FALSE, results='hide')
options(formatR.arrow=TRUE,width=90)
@

\begin{document}

\maketitle

<<initial_stuff>>=
remake_models_bool = FALSE
recalculate_stats = TRUE
library(here)
if (remake_models_bool)
{
  source(here('analysis', 'data_io', 'io_toolbox.r'))
} else if (recalculate_stats) {
  source(here('analysis', 'paleo_geoms', 'test_differences.r'))
  source(here('analysis', 'analyzing_reworking', 'test_differences.r'))
  source(here('figures', 'src', 'piceance_manuscript_data_plot.r'))
}
load(here('data','data_summaries', 'paleo_geom.rda'))
load(here('data','data_summaries', 'paleo_pres.rda'))
load(here('data', 'data_summaries', 'avuls_summary.rda'))
@

\section{Abstract}

The Paleocene-Eocene Thermal Maximum (PETM) is the most extreme example of an abrupt climate perturbation in the Cenozoic, and is widely cited as an analog for contemporary climate change.
Accumulation of terrigenous mud in marginal shelf environments and concentration of sand of terrestrial deposits during the PETM are both used to infer an increase in total annual water and sediment discharge in fluvial systems.
However, recent geochemical proxies and climate models indicate an alternative scenario, wherein intra-annual runoff variability increased while mean annual precipitation remained unchanged.
Herein, we use measurements of channel geometry and sediment grain size, as well as interpretations of channel bar structures and avulsion style to assess the fluvial response to hydrological change during the PETM.
Strata in the Piceance Basin (Colorado, USA), indicate that channel depth and slope are consistent across the PETM interval, and sediment transport estimates using these data show that overall sediment flux did not appreciably change.
During the PETM, fluvial bar structures are poorly preserved, and avulsion style changes substantially versus before or after.
Both imply enhanced floodplain reworking due to intensified channel migration and avulsion.
Taken together, these results are consistent with a changing hydrological regime characterized by increased precipitation variability without a change in mean runoff.
As a consequence of enhanced fluvial reworking, bed material sediment was partitioned into floodplain deposits, while mud was preferentially remobilized and transported downstream as washload.
This interpretation explains sedimentological variations in PETM stratigraphy across depositional environments from source to sink without invoking sustained increases in mean sediment and water discharge.

\section{Introduction}

\R{A1} Contemporary global climate change is predicted to impact the hydrological cycle, threatening communities and infrastructure situated on river corridors \parencite[e.g.][]{dankers_climate_2008}.
The hazards posed by modern climate change are understood by analyzing the sedimentology and biogeochemical proxies preserved in continental margin stratigraphy, since both can be used to reconstruct hydrological changes in terrestrial environments \parencite[e.g.][]{slotnick_large_2012}.
However, stochastic sediment transport processes can distort and mask the signal of changing climate, hindering interpretations of the stratigraphic record \parencite{romans_environmental_2016, armitage_transformation_2011}.
Reconstructing past climate change based on the stratigraphic record therefore requires understanding how the hydrological cycle impacts sediment transport and accumulation in terrestrial settings.

The Paleocene Eocene Thermal Maximum (PETM) is the most severe climate perturbation known in the Cenozoic Era \parencite{zachos_early_2008}.
Characterized by precipitation extremes, rapid warming, and accumulation of atmospheric carbon \parencite{carmichael_hydrological_2017}, the PETM is considered one of the best geologic analogues for contemporary climate warming \parencite{mcinerney_paleocene-eocene_2011}.
The PETM is identified in strata around the world by a negative \del{13}{C}{} carbon isotope excursion \parencite{kennett_abrupt_1991}, and often coincides with drastic changes in sedimentology.
In marginal marine environments, the PETM is most commonly associated with increased deposition of terrigenous clay \parencite{john_north_2008, gibson_stratigraphic_2000}, which is attributed to elevated sediment flux from continents during the PETM: a candidate for a global-scale ``system-clearing'' event affecting sediment routing systems \parencite{foreman_fluvial_2012, jerolmack_shredding_2010}.

The mechanism driving a global increase in sediment flux in terrestrial evironments, though, is disputed.
Studies of terrestrial alluvial systems generally find that strata deposited during the PETM are channel-dominated and enriched in sand relative to bounding units \parencite[e.g.][]{pujalte_massive_2015}.
Differences in river channel geometries interpreted from the strata, including width and depth, as well as slope, are taken as evidence for a secular increase in channel-forming discharge, and therefore sediment flux, during the PETM \parencite{chen_estimating_2018, foreman_fluvial_2012}.
However, the paleohydraulic techniques used to reconstruct discharge in the geologic record carry significant uncertainty \parencite[$1.3\times$ to $14\times$ increase in][]{chen_estimating_2018}.

As a result, it remains unclear whether the sedimentological differences in PETM strata reflect an increase in the total annual sediment flux.
While channel-forming discharge averaged over annual to decadal time scales may have remained steady, runoff on short time scales might have been more variable, producing wetter wet seasons and drier dry seasons \parencite{schmitz_abrupt_2007}.
Evidence from modern systems and the rock record shows that ephemeral river systems characterized by intense seasonal runoff possess unique morphological and sedimentological characteristics as opposed to perennial rivers with less flow variability \parencite{plink-bjorklund_morphodynamics_2015, fielding_role_2018}.
Additionally, \textcite{esposito_sediment_2018} showed experimentally that introducing intense flooding while holding overall water and sediment flux constant causes channels to migrate rapidly and avulse more frequently.
Accelerated channel kinematics promoted floodplain reworking, concentrating channel deposits in the strata.
Channel-dominated floodplain deposits observed in PETM strata \parencite{pujalte_massive_2015, foreman_climate-driven_2014} could potentially have arisen either from (1) a secular increase in water and sediment flux or through (2) intensified seasonal flooding with constant average discharge.
Distinguishing between these contrasting scenarios of fluvial response during the PETM is critical for interpreting paleoclimate, as each carries different implications for sediment dispersal patterns and biogeochemical proxy responses \parencite{straub_influence_2013, esposito_sediment_2018}.

\section{Study Locality}

In this study, we revisit the well-studied Piceance Basin (Colorado, USA; Figure \ref{fig:map}), where changes in channel stacking patterns and sand enrichment have been attributed to an increase in water and sediment flux during the PETM \parencite{foreman_fluvial_2012}.
As an intermontane Laramide depocenter active throughout the Paleogene \parencite{johnson_history_2003}, sedimentary fill of the Piceance Basin is conformable across the Paleocene-Eocene boundary.
The PETM interval is marked in the Piceance Basin by a stable carbon isotope excursion, correlating with a distinctive sand-rich unit known as the Molina Member of the Wasatch Formation \parencite{foreman_fluvial_2012}.
\cnote[add Burger]

Juxtaposed between mud-rich units, sedimentological characteristics of the sandy Molina Member contrast starkly with the underlying Atwell Gulch and the overlying Shire Members of the Wasatch \parencite{donnell_paleocene_1969} \cnote[add lorenz and nadon, foreman2012].
While the Atwell Gulch and Shire Members largely consist of a matrix of muddy floodplain paleosols encasing isolated channel sand bodies, the Molina Member comprises interconnected, sheetlike amalgamated sand bodies with relatively thin intervening layers of floodplain mud (Figure \ref{fig:outcrops}).
\textcite{foreman_fluvial_2012} interpret distinctive sedimentology in the Molina Member, including upper-stage plane bed structures as well as deeper and wider channels, as a fluvial response to enhanced monsoonal precipitation.

However, other lines of evidence suggest that the Piceance Basin did not experience an increase in runoff, but rather an increase in precipitation variability.
For example, climate model simulations predict overall drying conditions across the American Mountain West during the PETM \parencite{carmichael_hydrological_2017}, and paleosol records in the Piceance Basin \parencite{erhardt_relative_2005} and nearby Bighorn Basin \parencite{kraus_transient_2007} support the notion that regional annual precipitation did not increase, and may have actually decreased slightly.
Paleobotanical evidence for vegetation community overturn in the Bighorn Basin and sedimentological interpretations of coeval strata from the neighboring Uinta Basin both suggest a regional increase in runoff seasonality \parencite{wing_plant_2013, birgenheier_climate_2020}.
What remains is to rectify the apparent contradiction between observations of long-term steady average discharge and interpreted increases in sediment flux and river channel capacity in the Piceance Basin.

\section{Methods}

This study uses new estimates of channel paleo-geometries and kinematics to constrain the fluvial response to the PETM in the Piceance Basin.
We quantified four key paleohydraulic parameters: (1) channel flow depth, (2) fluvial slope, (3) lateral migration, and (4) avulsion style.
Data were collected during three field campaigns from 2017--2019, as well as aggregated from previous literature and unpublished sources.

Estimates of paleo-flow depth through the Wasatch Formation were obtained by measuring the relief on fully preserved fluvial barforms and channel fill structures for a total of \Sexpr{nnew} new flow depth estimates, nearly doubling the existing dataset \parencite{ethridge_reconstructing_1977, mohrig_interpreting_2000}.
Paleo-flow depths from bar clinoforms were combined with co-located measurements of bedload sediment size, interpreted using a hand lens and grain-size card, to estimate paleoslope via the empirical scaling of \textcite{trampush_empirical_2014}.
Paleo-flow depth and slope constrain bankfull channel geometry \parencite{mohrig_interpreting_2000, lynds_paleoslope_2014}, and are generally considered to be sensitive to trends in discharge \parencite{leopold_hydraulic_1953}.

To quantify the effect of short-term variability of runoff, avulsion style and lateral migration rate were estimated through the Wasatch Formation by classifying avulsion and bar deposits.
Drone imagery was collected for three outcrops in the Piceance Basin, and photogrammetry was used to construct 3D digital models of the outcrop surface.
Bar clinoforms were mapped on the 3D digital outcrops, and barforms were classified as either fully preserved, partially preserved, or truncated (example interpretations in Figure \ref{fig:outcrops}).
As channels laterally migrate, previously deposited sediment is reworked, so the abundance of poorly preserved or truncated bars in channel deposits can indicate the rate of channel migration in the floodplain relative to the rate of subsidence \parencite{chamberlin_using_2019}.
The basal contact of a fluvial sandbody represents an avulsion event that is either preceded abruptly (without crevasse splays) or transitionally (with splays) \parencite{jones_characterizing_2007}.
We classified avulsions from field observations in all three Members of the Wasatch formation using criteria in \textcite{jones_characterizing_2007}.
Transitional-style avulsions in an alluvial basin may indicate more active crevassing in the channel-floodplain system \parencite{hajek_is_2014}, while stratigraphically abrupt avulsions may indicate less active crevassing.

\section{Results}

The data indicate that paleoflow depths are statistically indistinguishable throughout the Wasatch Formation at a 95\% confidence level (Table \ref{tab:paleo_geom} and Figure \ref{fig:paleo_geom}a).
Additionally, estimates of paleoslope in the Piceance Basin indicate no difference between the Molina Member and the bounding Members at a 95\% confidence level (Figure \ref{fig:paleo_geom}b).
Shields parameter estimates using the combined depth-slope product shows that within uncertainty, sediment transport was also consistent over geologic time between the Molina and the bounding Members (see Table \ref{tab:paleo_geom}).
Together, these results demonstrate that within the resolution of currently available paleohydraulic methods, sediment flux was consistent, and rivers were likely not substantially deeper or steeper during the PETM (Molina) as opposed to before (Atwell Gulch) or after (Shire).

Mapping of sedimentary structures throughout the Wasatch Formation shows that in the Molina Member, \Sexpr{signif(pres$meanPres[2], digits = 3)}\% of barforms are fully preserved, whereas in the Atwell Gulch and Shire Members, \Sexpr{signif(pres$meanPres[1], digits = 3)}\% and \Sexpr{signif(pres$meanPres[3], digits = 3)}\% of barforms are fully preserved, respectively (Figure \ref{fig:paleo_geom}c).
A~$\chi^2$~test shows that there are significantly fewer fully preserved barforms in the Molina Member ($\chi^2$(\Sexpr{barpres_test$parameter},~n~=~\Sexpr{sum(barpres_test$observed)})~=~\Sexpr{signif(barpres_test$statistic, digits = 3)}, $\Sexpr{p_comp_reworking}$ (2-tailed)), indicating that barforms in the Molina Member crosscut each other more frequently than in either the Shire or Atwell Gulch Members.

Our data also indicate that avulsion style changed during Molina time.
Stratigraphically transitional avulsions were more abundant than abrupt avulsions in the Molina Member, as compared to the Shire and Atwell Gulch Members ($\chi^2$(\Sexpr{avultest$parameter},~n~=~\Sexpr{sum(avultest$observed)})~=~\Sexpr{signif(avultest$statistic, digits = 3)}, $\Sexpr{p_comp_avulsion}$ (2-tailed)).
This indicates that avulsions were more likely to occur via progradation and channel building by crevasse splays, rather than by incision into the floodplain.

\section{Discussion}

The preponderance of truncated and partially preserved fluvial bar deposits we observe in the Molina Member is indicative of enhanced fluvial reworking during the PETM as compared to the intervals before (Atwell Gulch) and after (Shire).
In order to rework existing channel deposits before they subside below the river incision depth, river channels during Molina time must have revisited locations on the floodplain frequently relative to the subsidence rate \parencite{chamberlin_using_2019}.
Given that tectonic subsidence in the Piceance Basin appears stable throughout the PETM \parencite{foreman_fluvial_2012}, enhanced fluvial reworking of floodplain deposits implies that channel migration rates accelerated as a result of changing hydroclimate.

While channel migration rates are sensitive to changes in long-term average water and sediment discharge \parencite{hickin_lateral_1984}, our other data do not support a secular increase in annual runoff.
Paleo-flow depth and slope data both indicate that channel geometries did not adjust to convey greater discharge as a result of the PETM.
As depth and slope are first-order controls on sediment flux, calculating the Shields parameter from these data shows that sediment flux also did not change within uncertainty (see Table \ref{tab:paleo_geom}).
We therefore interpret that the long-term average runoff and sediment flux in the Piceance Basin were practically stable.
This is also in agreement with paleosol studies and climate model results, which point to consistent mean annual runoff throughout the PETM in the Rocky Mountain region.

On the other hand, climate models suggest that short-term runoff variability did increase during the PETM, and evidence for more active bar reworking in the Molina Member supports this assessment.
We propose that intervals of high-intensity flow would have exerted higher shear stress on channel banks, promoting enhanced erosion and accelerated lateral migration \parencite{konsoer_length_2017}.
Additionally, elevated bed shear stress during intensified flooding would have enhanced bed material entrainment, such that overbank flows transported coarse material to build crevasse splays, in agreement with our finding that avulsions were more likely to be stratigraphically transitional during the PETM.
While our data do not directly connect discharge variability with peak shear stress conditions driving channel mobility and avulsions, the channel-dominated strata and lack of bar preservation in the Molina Member parallel observations from modern systems and experimental studies \parencite{fielding_role_2018, esposito_sediment_2018}.

The effect of increased lateral mobility and crevasse-dominated avulsions was a net enrichment of floodplain strata with coarse bed material.
Migrating channels reworked near-surface deposits, preferentially coarsening sediment by entraining fines and transporting them downstream, while bed material partitioned into floodplain deposits.
In this way, mud bypassed the floodplain through morphodynamic reworking, while sand was retained in the basin.
The Shire and Atwell Gulch typify the opposite scenario, where accumulation of mud in overbank environments and evidence for less reworking indicates slower channel migration and infrequent crevassing.
Both are interpreted to be the result of a lack of discharge variability, and as a result, coarse material was confined to channels, bypassing the floodplain and depositing in downstream basins.

In this framework, enhanced floodplain reworking retains sand proximally, while mud bypasses and accumulates in distal basins, resulting in an accentuated downstream grain size gradient.
Stepping back broadly, the trend is borne out in other studies of PETM deposits, where proximal intermontane basins like the Piceance and Bighorn record an increase in grain size, while continental margins exhibit an increase in terrigenous mud accumulation during the PETM.
This model of fluvial response to changing hydroclimate during the PETM explains broad trends across depositional environments without requiring a continent-scale increase in sediment and water flux.

\section{Conclusions and Implications}

In this study, paleohydraulic techniques were applied in the Piceance Basin of western Colorado to constrain changes in channel-floodplain processes connected with abrupt climate change during the PETM.
The analyses indicate that fluvial channel geometries including depth and slope are consistent across the PETM boundary.
However, fluvial structures are more often truncated and cross-cut during the PETM interval, and avulsions become transitional in nature.
Taken together with experimental and observational studies of discharge variability and paleoclimate evidence from the region, these findings suggest that sedimentological shifts during the PETM in the Piceance Basin are not driven by secular increases in water and sediment flux, but rather by accelerated channel migration and a shift in avulsion style.

The Piceance Basin serves as an example that, all else being equal, terrestrial floodplains subjected to seasonally intense precipitation experience accelerated channel dynamics, allowing rivers to rework floodplain deposits, enriching the stratigraphy in sand, while reworked mud and silt bypasses downstream.
In contrast, channels in alluvial basins with low discharge variability act as conduits for sand bypass, while terrestrial floodplains accumulate mud in overbank deposits.
This framework is advanced as an alternative to the global system-clearing model of PETM landscape response, emphasizing that shifting hydrological regimes under global warming need not invoke transiently high sediment fluxes, but rather may simply re-apportion sediment through morphodynamic sorting.

\newpage

\begin{figure}[H]
	\centering
	\includegraphics[width = 6in, draft = false]{manuscript_map.pdf}
	\begin{minipage}{0.9\textwidth}
	\vspace*{2mm}
	\caption{Inset: The Piceance Basin shown in dark gray superimposed on the US state of Colorado.
  Map: The Wasatch Formation is exposed as shown in the gray shading on the map, surrounding the town of De Beque, and outcropping along the I-70 corridor.
  Color-coded dots with white outlines indicate outcrops that were analyzed for this study, color-coded diamonds with black outlines are locations of photographs in Figure \ref{fig:outcrops}.
  Yellow signifies the Shire, green the Molina, and dark blue the Atwell Gulch Member.
  Location data for all outcrops and measurements is included in the data repository.
  }
	\label{fig:map}
	\end{minipage}
\end{figure}

\begin{figure}[H]
	\centering
	\includegraphics[width = 4.5in, draft=false]{annotated_outcrops_figure.pdf}
	\begin{minipage}{0.9\textwidth}
	\vspace*{2mm}
	\caption{Example outcrops showing key sedimentological features in each Member of the Wasatch Formation.
  Color-coded lines indicate high-order bounding surfaces between channel stories, whereas the white lines in each photograph indicate bar faces and scour surfaces.
  Note the neatly stacking clinoform bar faces in the Atwell Gulch and Shire Members, indicating full preservation.
  In contrast, extensively cross-cutting bar scours and faces in the Molina Member indicate scour and truncation.
  Locations for photographs are shown on Figure \ref{fig:map}}
	\label{fig:outcrops}
	\end{minipage}
\end{figure}

\begin{figure}[H]
	\centering
	\includegraphics[width = \textwidth, draft=false]{petm_data.pdf}
	\begin{minipage}{0.9\textwidth}
	\vspace*{2mm}
	\caption{Estimates of paleohydraulic parameters in the Piceance Basin.
  Paleoflow depth estimates from all sources are consistent across all three Members of the Wasatch Formation, as is paleoslope.
  The Molina Member shows significantly fewer fully preserved bars as opposed to the Atwell Gulch or Shire Members.
  Additionally, the Molina Member experiences many more transitional-type avulsions.
  Vertical lines represent the measured proportion of fully preserved bars.
  The shaded histograms represent bootstrapped values to visualize the standard error.
  Statistics and values found in Table \ref{tab:paleo_geom}.}
	\label{fig:paleo_geom}
	\end{minipage}
\end{figure}

\clearpage

\begin{sidewaystable}
% \centering
\caption{Data for Wasatch Formation in the Piceance Basin.
Included for each Member of the Formation are paleoflow depths measured from barforms, paleoslopes, first order estimates of shields number, the proportion of fully preserved bars, the prevalence of transitional avulsions, and the associated uncertainty for each term.
The second part of the table indicates significance values for Conover-Iman tests comparing flow depths and slope in different Members of the Wasatch Formation, as well as results from a $\chi^2$ test for the proportion of fully preserved bars and abundance of avulsion styles.}
\begin{tabular}{llllll}
Formation & Depth (m) $\pm \sigma$  & Slope (--) $\pm \sigma$ & Shields number (--) $\pm \sigma$ & \% Fully Preserved Bars $\pm \sigma$ & \% Transitional Avulsions  $\pm \sigma$\\
\hline
Shire         &
\Sexpr{signif(geoms$meanDepth[3], digits = 3)} $\pm$ \Sexpr{signif(geoms$sdDepth[3], digits = 3)}  &
\Sexpr{signif(geoms$meanSlope[3], digits = 3)} $\pm$ \Sexpr{100*signif(geoms$sdSlope[3] / geoms$meanSlope[3], digits = 3)}\% &
\Sexpr{signif(geoms$meanTau[3], digits = 3)} $\pm$ \Sexpr{signif(geoms$sdTau[3], digits = 3)} &
\Sexpr{signif(pres$meanPres[3], digits = 3)} $\pm$ \Sexpr{signif(pres$sdPres[3], digits = 3)} &
\Sexpr{signif(100*avuls_summary$meanAvul[3], digits = 3)} $\pm$ \Sexpr{100*signif(avuls_summary$sdAvul[3], digits = 3)} \\
Molina        &
\Sexpr{signif(geoms$meanDepth[2], digits = 3)} $\pm$ \Sexpr{signif(geoms$sdDepth[2], digits = 3)}  &
\Sexpr{signif(geoms$meanSlope[2], digits = 3)} $\pm$ \Sexpr{100*signif(geoms$sdSlope[2] / geoms$meanSlope[2], digits = 3)} \% &
\Sexpr{signif(geoms$meanTau[2], digits = 3)} $\pm$ \Sexpr{signif(geoms$sdTau[2], digits = 3)}  &
\Sexpr{signif(pres$meanPres[2], digits = 3)} $\pm$ \Sexpr{signif(pres$sdPres[2], digits = 3)} &
\Sexpr{signif(100*avuls_summary$meanAvul[2], digits = 3)} $\pm$ \Sexpr{signif(100*avuls_summary$sdAvul[2], digits = 3)} \\
Atwell Gulch  &
\Sexpr{signif(geoms$meanDepth[1], digits = 3)} $\pm$ \Sexpr{signif(geoms$sdDepth[1], digits = 3)}  &
\Sexpr{signif(geoms$meanSlope[1], digits = 3)} $\pm$ \Sexpr{100*signif(geoms$sdSlope[1] / geoms$meanSlope[1], digits = 3)} \% &
\Sexpr{signif(geoms$meanTau[1], digits = 3)} $\pm$ \Sexpr{signif(geoms$sdTau[1], digits = 3)}  &
\Sexpr{signif(pres$meanPres[1], digits = 3)} $\pm$ \Sexpr{signif(pres$sdPres[1], digits = 3)} &
\Sexpr{signif(100*avuls_summary$meanAvul[1], digits = 3)} $\pm$ \Sexpr{signif(100*avuls_summary$sdAvul[1], digits = 3)} \\
\hline
Atwell Gulch -- Molina  & $\Sexpr{p_comp_AG_M}$ & $\Sexpr{p_comp_AG_M_slope}$ & -- &
\multirow{3}{*}{$\Sexpr{p_comp_reworking}$} & \multirow{3}{*}{$\Sexpr{p_comp_avulsion}$} \\
Shire -- Molina         & $\Sexpr{p_comp_AG_S}$ & $\Sexpr{p_comp_AG_S_slope}$  & -- & & \\
Atwell Gulch -- Shire   & $\Sexpr{p_comp_S_M}$  & $\Sexpr{p_comp_S_M_slope}$   & -- & & \\
\hline
\end{tabular}
\label{tab:paleo_geom}
\end{sidewaystable}

\clearpage

\printbibliography
%
\end{document}
